services:
  waitkue-server:
    build: ./
    ports:
      - 80:80
    volumes:
      - ./:/code/
    depends_on:
      - database
    networks:
      - web-network
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: waitkue
    ports:
      - target: 3306
        published: 3306
    volumes:
    - type: volume
      source: data
      target: /var/lib/mysql
    networks:
      - web-network

  db_ui:
    image: shyim/adminerevo
    ports:
      - target: 8080
        published: 8080
    environment:
      ADMINER_DEFAULT_DRIVER: mysql
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DEFAULT_DB: waitkue
      ADMINER_DEFAULT_USER: root
      ADMINER_DEFAULT_PASSWORD: root
      ADMINER_DESIGN: dracula
    networks:
      - web-network

volumes:
  data:

networks:
  web-network:
    name: web-network
    external: true